#!/usr/bin/env python3

import boto3
import sys
import os
from urllib.parse import urlparse

def list_files(bucket_name, prefix):
    s3 = boto3.client('s3')
    paginator = s3.get_paginator('list_objects_v2')

    page_iterator = paginator.paginate(Bucket=bucket_name, Prefix=prefix)

    for page in page_iterator:
        for obj in page.get('Contents', []):  # Safeguard for empty contents
            print(obj['Key'])

def parse_s3_url(s3_url):
    parsed_url = urlparse(s3_url)
    if parsed_url.scheme != 's3':
        raise ValueError("URL must be an S3 URL starting with s3://")
    bucket_name = parsed_url.netloc
    prefix = parsed_url.path.lstrip('/')  # Remove leading slash for correct prefix
    return bucket_name, prefix

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print("Usage: aws_s3_list_all_filenames <profile_name> <region> <s3-url>")
        sys.exit(1)

    profile_name = sys.argv[1]
    region = sys.argv[2]
    s3_url = sys.argv[3]

    # Set AWS profile and region environment variables
    os.environ['AWS_PROFILE'] = profile_name
    os.environ['AWS_DEFAULT_REGION'] = region

    # Parse the S3 URL to get the bucket name and prefix
    bucket_name, prefix = parse_s3_url(s3_url)

    # Call list_files with the bucket name and prefix
    list_files(bucket_name, prefix)
