#!/usr/bin/php
<?php
while($os = fgets(STDIN)) {
	/// If we get cases with multiple IPs, like:
	///   73.26.121.203, 73.26.121.203, 10.20.14.60 - - [01/May/2015:06:54:57 -0600] "GET /files/h/40ad8f8eaeee.jpg HTTP/1.1" 200 10255 "-" "Mozilla/5.0 (Macintosh; Intel Mac ...
	///   unknown, 82.145.46.102, 82.145.46.102, 10.20.14.60 - - [03/May/2015:18:51:09 -0600] "GET /index/big-cookie-sign-up/ HTTP/1.1" 200 1426 "-" "Mozilla/5.0 (compatible; ...
	///   , 206.83.48.110, 206.83.48.110, 10.20.14.61 - - [03/May/2015:19:36:16 -0600] "GET /files/categories/214_menu.jpg HTTP/1.1" 200 14925 "-" "Mozilla/4.0 (compatible;)"
	///   2601:8:400:b8c8:bc62:5b61:6464:9776, 66.249.83.208, 66.249.83.208, 10.20.14.60 - - [03/May/2015:20:11:30 -0600] "GET /blogs/wp-includes/images/custom/franchise.jpg H...
	# $os = preg_replace(
	# 	'/^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
	# 	. '(,\s*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})*'
	# 	. '/',
	# 	'$1',$os);
	$os = preg_replace(
		'/^'
		. '.*?'
		. '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}),'
		. '\s*'.  '10.'.  '\d{1,3}\.\d{1,3}\.\d{1,3}'
		. '([^\d,])'
		. '/',
		'$1$2',$os);

	$s = explode(' ',rtrim($os));
	array_unshift($s, $s[5]);
	array_unshift($s,$s[7]);
	array_unshift($s,
		$s[2][0] == '['
		? date("Y-m-d H:i:s",strtotime(trim($s[2]." ".$s[3]." ".$s[4]." ".$s[5]." ".$s[6],"/\[\]/")))
		: date("Y-m-d H:i:s",strtotime(trim($s[5]." ".$s[6],"/\[\]/")))
		);
	print(join(" ",$s)).'|||---|||'.rtrim($os)."\n";
}
