#!/usr/bin/env python3

import boto3
import sys
import os

def list_codebuild_projects(region, profile):
    session = boto3.Session(profile_name=profile, region_name=region)
    codebuild_client = session.client('codebuild')

    # Get all the CodeBuild projects
    projects = codebuild_client.list_projects()['projects']

    for project in projects:
        project_details = codebuild_client.batch_get_projects(names=[project])['projects'][0]
        print(f"Project: {project}")

        # Check if the source type is GITHUB
        if project_details['source']['type'] == 'GITHUB':
            source = project_details['source']
            print(f"Repository: {source['location']}")

            if 'buildspec' in source:
                print(f"Build Spec File: {source['buildspec']}")

            # Fetch Webhook details if available
            if 'webhook' in project_details:
                webhook = project_details['webhook']
                print(f"Webhook URL: {webhook['url']}")
                
                if 'filterGroups' in webhook:
                    for group in webhook['filterGroups']:
                        for filter in group:
                            print(f"Filter Type: {filter['type']}")
                            print(f"Filter Pattern: {filter['pattern']}")
                            if 'excludeMatchedPattern' in filter:
                                if filter['excludeMatchedPattern']:
                                    print("This pattern is excluded.")
                                else:
                                    print("This pattern is included.")
                
                if 'eventTypes' in webhook:
                    for event in webhook['eventTypes']:
                        print(f"Webhook event type: {event}")
        print("---------------------------")

    print("Done listing projects.")

def main():
    # Check command line arguments
    if len(sys.argv) < 2:
        print("Usage: aws_codebuild_ls <region> [profile]")
        sys.exit(1)

    region = sys.argv[1] if len(sys.argv) > 1 else 'us-east-1'
    profile = sys.argv[2] if len(sys.argv) > 2 else 'default'

    os.environ['AWS_PROFILE'] = profile
    os.environ['AWS_REGION'] = region

    list_codebuild_projects(region, profile)

if __name__ == '__main__':
    main()
