#!/usr/bin/env python3

import boto3
import sys
import os

def list_secrets(region, profile):
    # Set up boto3 session using provided profile
    session = boto3.Session(profile_name=profile, region_name=region)
    
    # Create a client for the Secrets Manager service
    secrets_client = session.client('secretsmanager')
    
    secrets = []
    next_token = None

    # Get the list of secrets
    while True:
        if next_token:
            response = secrets_client.list_secrets(NextToken=next_token)
        else:
            response = secrets_client.list_secrets()
        
        secrets.extend(response.get('SecretList', []))

        next_token = response.get('NextToken')
        if not next_token:
            break
    
    return secrets


def main():
    # Check command line arguments
    if len(sys.argv) < 2:
        print("Usage: aws_secrets_ls <region> [profile]")
        sys.exit(1)

    region = sys.argv[1] if len(sys.argv) > 1 else 'us-east-1'
    profile = sys.argv[2] if len(sys.argv) > 2 else 'default'

    os.environ['AWS_PROFILE'] = profile
    os.environ['AWS_REGION'] = region
    
    secrets = list_secrets(region, profile)
    
    if not secrets:
        print(f"No secrets found in region {region} for profile {profile}.")
        return
    
    print(f"Secrets in region {region} for profile {profile}:")
    for secret in secrets:
        secret_name = secret.get('Name', 'N/A')
        description = secret.get('Description', 'N/A')
        last_accessed_date = secret.get('LastAccessedDate', 'N/A')
        # ... Add more attributes as needed
        print(f"Name: {secret_name}, Description: {description}, Last Accessed Date: {last_accessed_date}")

if __name__ == '__main__':
    main()
