#!/usr/bin/perl -w

#########################
###  makep_sym
#
# Version : $Id: makep_sym,v 1.3 2011/05/23 16:26:38 dave Exp $
#
#########################

###  Pragmas
use strict;

#########################
###  Configuration, Setup

use Term::Complete;

###  Globals
my $SYSTEM_PROJECT_BASE = $ENV{SYSTEM_PROJECT_BASE} || '/sandbox/projects';
###  The projects directory
my $projects_directory = "$ENV{HOME}/work/projects";

###  Default symlinks
my %default_symlinks = ( 
#                         'links/p1' => "$ENV{HOME}/tsanet/sites/community.tsanet.org",
#                         'links/p2' => "$ENV{HOME}/tsanet/lib/ctl/secure",
#                         'links/p3' => "$ENV{HOME}/tsanet/sites/community.tsanet.org",
#                         'links/p4' => "$ENV{HOME}/tsanet/",
#                         'links/p5' => "$ENV{HOME}/tsanet/",
#                         'links/p6' => "$ENV{HOME}/tsanet/",
#                         'links/p7' => "$ENV{HOME}/tsanet/",
#                         'links/p8' => "$ENV{HOME}/tsanet/",
#                         'links/p9' => "$ENV{HOME}/tsanet/",
                         );


#########################
###  Main Runtime

###  Assemble the date from one of the matched formats above
###    or from the current date if they're all empty
my ($y, $m, $d) = ( (( localtime )[5] + 1900), (( localtime )[4] + 1), ( localtime )[3] );

###  Fix the date parameters
my $project_date = sprintf("%.4d", $y) . '-' . sprintf("%.2d", $m) . '-' . sprintf("%.2d", $d);

###  Just use the name as is
my $project_name = $ARGV[0];

###  Set the $new_project name
# my $new_project = "$project_date\_$project_name";
my $new_project = $project_name;

###  Error out if the $new_project already exists
die "New Project already created..." if -e "$projects_directory/$new_project";


###  Create the project directory and it's /links dir
`ln -s $SYSTEM_PROJECT_BASE/$project_name $projects_directory/$new_project`;
mkdir "$projects_directory/$new_project/links", 0777;



###  Setup %default_symlinks
foreach ( keys %default_symlinks ) { 

  ###  Symlink
  symlink( $default_symlinks{ $_ }, "$projects_directory/$new_project/$_" ) || warn "Symlinking of default $projects_directory/$new_project/$_ to $default_symlinks{ $_ } failed : $!";
}

exit 0;
