#!/usr/bin/perl -w

my @f1;
if ( open F1, $ARGV[0] ) {
  @f1 = map { chomp;  $_ * 1; } <F1>;  
  close F1;  
}

my @f2;
if ( open F2, $ARGV[1] ) {
  @f2 = map { chomp;  $_ * 1; } <F2>; 
  close F2;  
}  

my $buffer = $ARGV[2] || 0;


foreach (@f1) { 

  while ( 
          ( @f2 ) && 
          ( $f2[0] < $_ ) 
          ) { 
    shift @f2;
  }  
  print( 
         rcs_date( $_, ( $buffer * -60 ) ) . 
         " < " . 
         rcs_date( $f2[0], ( $buffer * 60 ) ) . 
         "\n");  

  shift @f2;
  
}


sub rcs_date {

  ###  Get the parameters passed to us
  my ( $time ) = shift || time();

  ###  Do the Adjustment
  $time += shift || 0;


  ###  Return the date in the right format
  ###   Example: 1990-01-11 20:00:00-06
  my @l = localtime( $time + ( 3600 * 6 ) );
  ( 
    sprintf("%.4d", ( 1900 + $l[5] ) ) .
    '-' . 
    sprintf("%.2d", ( $l[4] + 1 ) ) .
    '-' . 
    sprintf("%.2d", $l[3] ) .
    ' ' . 
    sprintf("%.2d", ( ( $l[2] + 1 ) % 24 ) ) .
    ':' . 
    sprintf("%.2d", $l[1] ) .
    ':' . 
    sprintf("%.2d", $l[0] ) .
    '-06' 
    );
}
