#!/bin/bash -norc

#########################
###  project_list
#
# Version : $Id: project_list,v 1.1 2011/05/23 15:57:29 dave Exp $
#
#########################

#########################
###  Configuration, Setup

# ###  Globals
# export SYSTEM_PROJECT_BASE='/sandbox/projects'


#########################
###  Main Runtime

echo "  "
echo "All Active Projects:"
echo "--------------------"
ls -1 $SYSTEM_PROJECT_BASE | grep -E -v '^archive$'