#!/bin/bash

#########################
###  INSTALLATION
#  
#  To Install:
#  -----------
#  
#  1) Copy everything below this section into an rc file for bash
#     (.bashrc, .login or .profile)
#  
#  2) Read through the config sections below and tweak for your
#     preferences (e.g. emacs vs. vim preferences, etc.)
#  
#  3) Get trained by someone on how to use the new Project System
#  
#########################

#########################
###  Project System Setup

export     SYSTEM_TMP_BASE="/sandbox/$USER/myproject_tmp"
export SYSTEM_PROJECT_BASE=/sandbox/projects
###  CVS Repo Settings
#export SYSTEM_CVS_BASE_REGEXP="$HOME/public_html/.sites/.sandbox/\w+/myproject"
export SYSTEM_CVS_BASE="$HOME/sandbox/dave/myproject"
export      P_BIN_PATH=$SYSTEM_CVS_BASE/admin/bin

###  Paths to CVS
# export PATH="$SYSTEM_BIN_PATH:$PATH"

######  Modify PATH to include the project bin dirs
###  The project system files
export PATH="$P_BIN_PATH:$PATH"

###  CVS helps: uncomment this if you want them
###    NOTE: these don't currently have docs, but 
###    as they are REALLY simple, try just looking
###    at the source.  Or go ask Dave.
# export PATH="$P_BIN_PATH/cvs_helps:$PATH"


#########################
###  Project Aliases
alias    preg=project_register
alias pcreate=project_create
alias pswitch=project_switch
alias   plist=project_list
alias    paff=project_affected_files
alias    psum=project_summary

# ###  Edit files (emacs preference)
# export EDITOR=emacs

###  ###  Operate on affected files
###  alias          aff_stat='cd $SYSTEM_CVS_BASE; export CUR_PROJECT_DIR=$SYSTEM_PROJECT_BASE/`cat ~/.current_project`; cvs status `egrep -x -v "\*{3}.+\*{3}" $CUR_PROJECT_DIR/affected_files.txt` | grep "Status:"'
###  alias      aff_proddiff='cd $SYSTEM_CVS_BASE; export CUR_PROJECT_DIR=$SYSTEM_PROJECT_BASE/`cat ~/.current_project`; cvs diff -c -rPROD_SAFE `cat $CUR_PROJECT_DIR/affected_files.txt`'
###  alias      aff_testdiff='cd $SYSTEM_CVS_BASE; export CUR_PROJECT_DIR=$SYSTEM_PROJECT_BASE/`cat ~/.current_project`; cvs diff -c -rTEST `cat $CUR_PROJECT_DIR/affected_files.txt`'
###  alias        aff_perlwc='cd $SYSTEM_CVS_BASE; export CUR_PROJECT_DIR=$SYSTEM_PROJECT_BASE/`cat ~/.current_project`; cat $CUR_PROJECT_DIR/affected_files.txt | egrep -v '\''\.(sql|tpl|html)$'\'' | ql | xargs -n1 perl -wc'
###  alias          aff_logh='cd $SYSTEM_CVS_BASE; export CUR_PROJECT_DIR=$SYSTEM_PROJECT_BASE/`cat ~/.current_project`; cat $CUR_PROJECT_DIR/affected_files.txt | ql | xargs -n1 cvs log -h'

