#!/usr/bin/perl -w

system('git', 'push', 'origin', `gcb`, @ARGV);

#set str = ''
#set i = 1
#while ($i <= $#)
#    echo $i
#    echo $argv[$i]
#    echo "WIG"
#    set str = "$str"' '`echo "${argv[$i]}" | perl -pe 's/([ \\])/\\$1/g'`''
#    echo "BAR: "$str
#    @ i = $i + 1
#end
#
#perl -e 'use Dave::Bug qw(:common);  bug(\@ARGV);' $str
